version: "3.9"
name: uok_chatbot

services:
  backend:
    build:
      context: ./Backend/Chatbot
      dockerfile: Dockerfile
    container_name: chatbot_app
    volumes:
      - ./Backend/Chatbot:/Chatbot
      - ./Backend/Chatbot/data:/data

    ports:
      - "8000:8000"   # Django API
    env_file:
      - ./Backend/Chatbot/.env
    environment:
      DJANGO_SETTINGS_MODULE: Chatbot.settings
      DB_HOST: pgvector
      DB_PORT: 5432
    depends_on:
      - pgvector

  pgvector:
    image: phidata/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5532:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/frontend/src
    environment:
      VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    depends_on:
      - backend

volumes:
  pgvolume: